DROP TABLE IF EXISTS categories CASCADE;
CREATE TABLE categories (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            name VARCHAR(100) NOT NULL,

                            slug VARCHAR(120) NOT NULL UNIQUE,

                            image_url VARCHAR(500),

                            is_active BOOLEAN NOT NULL DEFAULT TRUE
);
INSERT INTO categories (id, name, slug, image_url, is_active) VALUES
                                                                  (1, 'Laptop Gaming', 'laptop-gaming', '/uploads/categories/categories_laptop_gaming.webp', true),
                                                                  (2, 'Laptop Văn Phòng', 'laptop-van-phong', '/uploads/categories/categories_laptop_van_phong.webp', true),
                                                                  (3, 'Ultrabook Mỏng Nhẹ', 'ultrabook-mong-nhe', '/uploads/categories/categories_ultrabook_mong_nhe.jpg', true),
                                                                  (4, 'Laptop Đồ Họa', 'laptop-do-hoa', '/uploads/categories/categories_laptop_do_hoa.png', true),
                                                                  (5, 'Laptop Doanh Nhân', 'laptop-doanh-nhan', '/uploads/categories/categories_laptop_doanh_nhan.webp', true),
                                                                  (6, 'Laptop Sinh Viên', 'laptop-sinh-vien', '/uploads/categories/categories_laptop_sinh_vien.jpg', true);

ALTER TABLE products
    ADD CONSTRAINT fk_products_category
    FOREIGN KEY (category_id) REFERENCES categories (id);

SELECT setval(pg_get_serial_sequence('categories', 'id'), (SELECT MAX(id) FROM categories));