import { useMemo, useState, type FormEvent } from "react";
import { useMutation, useQueries, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Edit3, LoaderCircle, Search } from "lucide-react";
import { Link, useLocation, useParams, useSearchParams } from "react-router-dom";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "../../app/components/ui/dialog";
import { env } from "../../config/env";
import { adminApi } from "../api/adminApi";
import { AdminButton, AdminTable, fieldClassName, LoadingScreen, PageHeader, PaginationBar, Panel, StatusBadge, type AdminColumn } from "../components/AdminUI";
import { adminQueryKeys } from "../queryKeys";
import type { OrderHistoryResponse, OrderItemResponse, OrderResponse, OrderStatus, PaymentProvider, PaymentResponse, PaymentStatus } from "../types";
import { formatBackendDateTime, formatCurrency, getApiErrorMessage, orderTransitions } from "../utils";

const orderStatuses: OrderStatus[] = ["PENDING", "CONFIRMED", "SHIPPED", "DELIVERED", "RETURN_REQUESTED", "RETURNED", "REFUNDED", "CANCELLED"];

function OrderStatusDialog({ order, open, onOpenChange }: { order: OrderResponse | null; open: boolean; onOpenChange: (open: boolean) => void }) {
  const queryClient = useQueryClient();
  const [target, setTarget] = useState<OrderStatus | "">("");
  const [trackingNumber, setTrackingNumber] = useState("");
  const [error, setError] = useState<string | null>(null);
  const transitions = order ? orderTransitions[order.status].filter((status) => env.enableUnsafeOrderReturnTransitions || (status !== "RETURNED" && status !== "REFUNDED")) : [];
  const mutation = useMutation({
    mutationFn: () => adminApi.orders.updateStatus(order!.id, { status: target as OrderStatus, trackingNumber: target === "SHIPPED" ? trackingNumber.trim() : null }),
    onSuccess: () => { toast.success("Đã cập nhật trạng thái đơn hàng"); queryClient.invalidateQueries({ queryKey: ["admin", "orders"] }); queryClient.invalidateQueries({ queryKey: adminQueryKeys.dashboard }); onOpenChange(false); },
    onError: (mutationError) => setError(getApiErrorMessage(mutationError)),
  });
  const submit = (event: FormEvent) => { event.preventDefault(); setError(null); if (!target) return setError("Vui lòng chọn trạng thái mới"); if (target === "SHIPPED" && !trackingNumber.trim()) return setError("Tracking number là bắt buộc khi giao hàng"); mutation.mutate(); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="border-slate-200 bg-white text-slate-950"><DialogHeader><DialogTitle>Cập nhật đơn #{order?.id}</DialogTitle><DialogDescription className="text-slate-500">Trạng thái hiện tại: {order?.status}. Backend sẽ xác nhận transition cuối cùng.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={submit}>{error && <div role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<div><label className="mb-1.5 block text-sm font-bold text-slate-700">Trạng thái mới</label><select className={fieldClassName} value={target} onChange={(event) => setTarget(event.target.value as OrderStatus)}><option value="">Chọn trạng thái</option>{transitions.map((status) => <option key={status} value={status}>{status}</option>)}</select>{order && orderTransitions[order.status].some((status) => status === "RETURNED" || status === "REFUNDED") && !env.enableUnsafeOrderReturnTransitions && <p className="mt-2 text-xs font-semibold text-amber-700">RETURNED/REFUNDED bị khóa vì backend chưa expose API hoàn hàng/hoàn tiền an toàn.</p>}</div>{target === "SHIPPED" && <div><label className="mb-1.5 block text-sm font-bold text-slate-700">Tracking number *</label><input className={fieldClassName} maxLength={255} value={trackingNumber} onChange={(event) => setTrackingNumber(event.target.value)} /></div>} {target === "CANCELLED" && <div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-700">Hủy đơn có thể hoàn kho và coupon. Hãy kiểm tra kỹ trước khi xác nhận.</div>}<DialogFooter><AdminButton type="button" tone="secondary" onClick={() => onOpenChange(false)}>Đóng</AdminButton><AdminButton type="submit" tone={target === "CANCELLED" ? "danger" : "primary"} disabled={mutation.isPending || !target}>{mutation.isPending && <LoaderCircle className="h-4 w-4 animate-spin" />}Cập nhật</AdminButton></DialogFooter></form></DialogContent></Dialog>;
}

export function OrdersPage() {
  const [params, setParams] = useSearchParams();
  const [statusOrder, setStatusOrder] = useState<OrderResponse | null>(null);
  const page = Math.max(0, Number(params.get("page") ?? 0));
  const size = [10, 20, 50, 100].includes(Number(params.get("size"))) ? Number(params.get("size")) : 20;
  const status = (params.get("status") ?? "") as OrderStatus | "";
  const queryParams = useMemo(() => ({ page, size, status }), [page, size, status]);
  const query = useQuery({ queryKey: adminQueryKeys.resource("orders", queryParams), queryFn: () => status ? adminApi.orders.byStatus(status, { page, size, sort: "createdAt,desc" }) : adminApi.orders.list({ page, size, sort: "createdAt,desc" }), placeholderData: (previous) => previous });
  const updateParam = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); if (key !== "page") next.set("page", "0"); setParams(next); };
  const columns: AdminColumn<OrderResponse>[] = [
    { key: "order", header: "Đơn hàng", render: (order) => <div><Link to={`/admin/orders/${order.id}`} state={{ order }} className="font-extrabold text-slate-900 hover:text-indigo-600">#{order.id}</Link><p className="mt-1 text-xs text-slate-400">User #{order.userId}</p></div> },
    { key: "date", header: "Ngày tạo", render: (order) => formatBackendDateTime(order.createdAt) },
    { key: "amount", header: "Tổng tiền", render: (order) => <strong>{formatCurrency(order.finalAmount)}</strong> },
    { key: "shipping", header: "Vận chuyển", render: (order) => <div><p>{order.carrier || "—"}</p><p className="mt-1 text-xs text-slate-400">{order.trackingNumber || "Chưa có tracking"}</p></div> },
    { key: "payment", header: "Thanh toán", render: (order) => order.paymentProvider ?? "—" },
    { key: "status", header: "Trạng thái", render: (order) => <StatusBadge value={order.status} /> },
    { key: "actions", header: "Thao tác", render: (order) => <AdminButton tone="secondary" size="sm" disabled={orderTransitions[order.status].length === 0} onClick={() => setStatusOrder(order)}><Edit3 className="h-3.5 w-3.5" />Cập nhật</AdminButton> },
  ];
  return <><PageHeader title="Đơn hàng" description="Theo dõi đơn bán hàng và chuyển trạng thái theo state machine an toàn." /><Panel><div className="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative flex-1 sm:max-w-sm"><Search className="absolute left-3.5 top-3.5 h-4 w-4 text-slate-400" /><input className={`${fieldClassName} pl-10`} disabled placeholder="Backend chưa có API tìm kiếm đơn" /></div><select aria-label="Lọc trạng thái đơn" className={`${fieldClassName} sm:w-60`} value={status} onChange={(event) => updateParam("status", event.target.value)}><option value="">Tất cả trạng thái</option>{orderStatuses.map((item) => <option key={item} value={item}>{item}</option>)}</select></div><AdminTable rows={query.data?.content ?? []} columns={columns} isLoading={query.isLoading} error={query.isError ? getApiErrorMessage(query.error) : null} onRetry={() => query.refetch()} /><PaginationBar page={page} totalPages={query.data?.totalPages ?? 0} totalElements={query.data?.totalElements ?? 0} size={size} onPageChange={(value) => updateParam("page", String(value))} onSizeChange={(value) => updateParam("size", String(value))} /></Panel><OrderStatusDialog key={statusOrder?.id ?? "closed"} order={statusOrder} open={Boolean(statusOrder)} onOpenChange={(open) => !open && setStatusOrder(null)} /></>;
}

export function OrderDetailPage() {
  const { orderId } = useParams<{ orderId: string }>();
  const id = Number(orderId);
  const location = useLocation();
  const [statusOrder, setStatusOrder] = useState<OrderResponse | null>(null);
  const initialOrder = (location.state as { order?: OrderResponse } | null)?.order;
  const orderQuery = useQuery({ queryKey: adminQueryKeys.detail("orders", id), queryFn: () => adminApi.orders.detail(id), enabled: id > 0, initialData: initialOrder });
  const results = useQueries({ queries: [
    { queryKey: adminQueryKeys.resource("order-items", { orderId: id }), queryFn: () => adminApi.orderItems.byOrder(id, { page: 0, size: 100 }), enabled: id > 0 },
    { queryKey: adminQueryKeys.resource("order-histories", { orderId: id }), queryFn: () => adminApi.orderHistories.byOrder(id, { page: 0, size: 100 }), enabled: id > 0 },
    { queryKey: adminQueryKeys.resource("payments", { orderId: id }), queryFn: () => adminApi.payments.byOrder(id, { page: 0, size: 100 }), enabled: id > 0 },
  ] });
  if (orderQuery.isLoading || results.some((result) => result.isLoading)) return <LoadingScreen label="Đang tải dữ liệu đơn hàng..." />;
  const order = orderQuery.data ?? null;
  const items = (results[0].data?.content ?? []) as OrderItemResponse[];
  const histories = [...((results[1].data?.content ?? []) as OrderHistoryResponse[])].sort((a, b) => a.createdAt.localeCompare(b.createdAt));
  const payments = (results[2].data?.content ?? []) as PaymentResponse[];
  return <><PageHeader title={`Đơn hàng #${id}`} description="Chi tiết đơn, sản phẩm, lịch sử và thanh toán được tải trực tiếp từ backend." actions={<><Link to="/admin/orders"><AdminButton tone="secondary"><ArrowLeft className="h-4 w-4" />Danh sách</AdminButton></Link>{order && orderTransitions[order.status].length > 0 && <AdminButton onClick={() => setStatusOrder(order)}><Edit3 className="h-4 w-4" />Cập nhật trạng thái</AdminButton>}</>} />{orderQuery.isError && <div role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{getApiErrorMessage(orderQuery.error)}</div>}{order && <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Panel className="p-4"><p className="text-xs font-bold uppercase text-slate-400">Trạng thái</p><div className="mt-2"><StatusBadge value={order.status} /></div></Panel><Panel className="p-4"><p className="text-xs font-bold uppercase text-slate-400">Tổng tiền</p><p className="mt-2 text-xl font-black">{formatCurrency(order.finalAmount)}</p></Panel><Panel className="p-4"><p className="text-xs font-bold uppercase text-slate-400">Khách hàng</p><p className="mt-2 font-black">User #{order.userId}</p></Panel><Panel className="p-4"><p className="text-xs font-bold uppercase text-slate-400">Ngày tạo</p><p className="mt-2 font-bold">{formatBackendDateTime(order.createdAt)}</p></Panel></div>}
    <div className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><Panel><div className="border-b border-slate-200 p-5"><h2 className="font-extrabold text-slate-900">Sản phẩm trong đơn</h2></div><AdminTable rows={items} columns={[{ key: "product", header: "Sản phẩm", render: (item) => <div><p className="font-bold text-slate-900">{item.product?.name ?? "—"}</p><p className="text-xs text-slate-400">Variant #{item.productVariantId}</p></div> }, { key: "quantity", header: "SL", render: (item) => item.quantity }, { key: "price", header: "Giá mua", render: (item) => formatCurrency(item.priceAtPurchase) }, { key: "total", header: "Thành tiền", render: (item) => <strong>{formatCurrency(item.priceAtPurchase * item.quantity)}</strong> }]} error={results[0].isError ? getApiErrorMessage(results[0].error) : null} /></Panel><Panel className="p-5"><h2 className="font-extrabold text-slate-900">Timeline trạng thái</h2><div className="mt-5 space-y-0">{histories.map((history, index) => <div key={history.id} className="relative flex gap-3 pb-5">{index < histories.length - 1 && <span className="absolute left-[7px] top-4 h-full w-px bg-slate-200" />}<span className="relative mt-1 h-4 w-4 shrink-0 rounded-full border-4 border-indigo-100 bg-indigo-600" /><div><StatusBadge value={history.status} /><p className="mt-2 text-xs leading-5 text-slate-500">{history.description || "Không có mô tả"}</p><p className="mt-1 text-[11px] text-slate-400">{formatBackendDateTime(history.createdAt)}</p></div></div>)}{!histories.length && <p className="text-sm text-slate-400">Chưa có lịch sử</p>}</div></Panel></div>
    <Panel><div className="border-b border-slate-200 p-5"><h2 className="font-extrabold text-slate-900">Payment attempts</h2></div><AdminTable rows={payments} columns={[{ key: "id", header: "ID", render: (payment) => `#${payment.id}` }, { key: "provider", header: "Cổng", render: (payment) => payment.provider }, { key: "transaction", header: "Mã giao dịch", render: (payment) => payment.transactionNo || "—" }, { key: "amount", header: "Số tiền", render: (payment) => formatCurrency(payment.amount) }, { key: "status", header: "Trạng thái", render: (payment) => <StatusBadge value={payment.status} /> }, { key: "created", header: "Ngày tạo", render: (payment) => formatBackendDateTime(payment.createdAt) }]} error={results[2].isError ? getApiErrorMessage(results[2].error) : null} /></Panel><OrderStatusDialog order={statusOrder} open={Boolean(statusOrder)} onOpenChange={(open) => !open && setStatusOrder(null)} /></>;
}

export function PaymentsPage() {
  const [params, setParams] = useSearchParams();
  const [editing, setEditing] = useState<PaymentResponse | null>(null);
  const [form, setForm] = useState<{ provider: PaymentProvider; transactionNo: string; status: PaymentStatus } | null>(null);
  const [error, setError] = useState<string | null>(null);
  const queryClient = useQueryClient();
  const page = Math.max(0, Number(params.get("page") ?? 0)); const size = Number(params.get("size") ?? 20); const status = (params.get("status") ?? "") as PaymentStatus | "";
  const query = useQuery({ queryKey: adminQueryKeys.resource("payments", { page, size, status }), queryFn: () => status ? adminApi.payments.byStatus(status, { page, size }) : adminApi.payments.list({ page, size }), placeholderData: (previous) => previous });
  const updateParam = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); if (key !== "page") next.set("page", "0"); setParams(next); };
  const mutation = useMutation({ mutationFn: () => adminApi.payments.update(editing!.id, { orderId: editing!.orderId, provider: form!.provider, transactionNo: form!.transactionNo.trim() || null, status: form!.status }), onSuccess: (response) => { if (response.status === editing?.status) toast.info("Backend trả về payment không thay đổi"); else toast.success("Đã cập nhật thanh toán"); setEditing(null); queryClient.invalidateQueries({ queryKey: ["admin", "payments"] }); queryClient.invalidateQueries({ queryKey: ["admin", "orders"] }); }, onError: (mutationError) => setError(getApiErrorMessage(mutationError)) });
  const columns: AdminColumn<PaymentResponse>[] = [{ key: "id", header: "Giao dịch", render: (payment) => <Link className="font-extrabold text-indigo-600" to={`/admin/payments/${payment.id}`}>#{payment.id}</Link> }, { key: "order", header: "Đơn", render: (payment) => <Link className="font-bold text-indigo-600" to={`/admin/orders/${payment.orderId}`}>#{payment.orderId}</Link> }, { key: "provider", header: "Cổng", render: (payment) => payment.provider }, { key: "transaction", header: "Mã giao dịch", render: (payment) => payment.transactionNo || "—" }, { key: "amount", header: "Số tiền", render: (payment) => <strong>{formatCurrency(payment.amount)}</strong> }, { key: "status", header: "Trạng thái", render: (payment) => <StatusBadge value={payment.status} /> }, { key: "created", header: "Ngày tạo", render: (payment) => formatBackendDateTime(payment.createdAt) }, { key: "action", header: "Thao tác", render: (payment) => <AdminButton tone="secondary" size="sm" disabled={payment.status !== "PENDING"} onClick={() => { setEditing(payment); setForm({ provider: payment.provider, transactionNo: payment.transactionNo ?? "", status: payment.status }); setError(null); }}><Edit3 className="h-3.5 w-3.5" />Xử lý</AdminButton> }];
  return <><PageHeader title="Thanh toán" description="Chỉ payment PENDING được phép đổi sang SUCCESS hoặc FAILED. REFUNDED không được giả lập qua màn hình này." /><Panel><div className="flex justify-end border-b border-slate-200 p-4"><select className={`${fieldClassName} sm:w-60`} value={status} onChange={(event) => updateParam("status", event.target.value)}><option value="">Tất cả trạng thái</option>{["PENDING", "SUCCESS", "FAILED", "REFUNDED"].map((item) => <option key={item}>{item}</option>)}</select></div><AdminTable rows={query.data?.content ?? []} columns={columns} isLoading={query.isLoading} error={query.isError ? getApiErrorMessage(query.error) : null} onRetry={() => query.refetch()} /><PaginationBar page={page} totalPages={query.data?.totalPages ?? 0} totalElements={query.data?.totalElements ?? 0} size={size} onPageChange={(value) => updateParam("page", String(value))} onSizeChange={(value) => updateParam("size", String(value))} /></Panel><Dialog open={Boolean(editing)} onOpenChange={(open) => !open && setEditing(null)}><DialogContent className="border-slate-200 bg-white text-slate-950"><DialogHeader><DialogTitle>Xử lý payment #{editing?.id}</DialogTitle><DialogDescription className="text-slate-500">SUCCESS có thể xác nhận đơn; FAILED có thể hủy đơn và hoàn kho/coupon.</DialogDescription></DialogHeader>{form && <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); setError(null); mutation.mutate(); }}>{error && <div role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<div><label className="mb-1.5 block text-sm font-bold text-slate-700">Nhà cung cấp thanh toán</label><select className={fieldClassName} value={form.provider} onChange={(event) => setForm((value) => value && ({ ...value, provider: event.target.value as PaymentProvider }))}>{["VNPAY", "MOMO", "COD"].map((item) => <option key={item}>{item}</option>)}</select></div><div><label className="mb-1.5 block text-sm font-bold text-slate-700">Mã giao dịch</label><input className={fieldClassName} value={form.transactionNo} onChange={(event) => setForm((value) => value && ({ ...value, transactionNo: event.target.value }))} /></div><div><label className="mb-1.5 block text-sm font-bold text-slate-700">Kết quả</label><select className={fieldClassName} value={form.status} onChange={(event) => setForm((value) => value && ({ ...value, status: event.target.value as PaymentStatus }))}><option value="PENDING">PENDING</option><option value="SUCCESS">SUCCESS</option><option value="FAILED">FAILED</option></select></div><DialogFooter><AdminButton type="button" tone="secondary" onClick={() => setEditing(null)}>Đóng</AdminButton><AdminButton type="submit" disabled={mutation.isPending}>{mutation.isPending && <LoaderCircle className="h-4 w-4 animate-spin" />}Xác nhận</AdminButton></DialogFooter></form>}</DialogContent></Dialog></>;
}

export function PaymentDetailPage() {
  const { paymentId } = useParams<{ paymentId: string }>();
  const id = Number(paymentId);
  const query = useQuery({ queryKey: adminQueryKeys.detail("payments", id), queryFn: () => adminApi.payments.detail(id), enabled: id > 0 });
  if (query.isLoading) return <LoadingScreen label="Đang tải giao dịch thanh toán..." />;
  if (!query.data) return <Panel className="p-8 text-center text-rose-600">{getApiErrorMessage(query.error)}</Panel>;
  const payment = query.data;
  return <><PageHeader title={`Payment #${payment.id}`} description={`Giao dịch của đơn hàng #${payment.orderId}`} actions={<Link to="/admin/payments"><AdminButton tone="secondary"><ArrowLeft className="h-4 w-4" />Danh sách</AdminButton></Link>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Panel className="p-5"><p className="text-xs font-bold uppercase text-slate-400">Trạng thái</p><div className="mt-3"><StatusBadge value={payment.status} /></div></Panel><Panel className="p-5"><p className="text-xs font-bold uppercase text-slate-400">Số tiền</p><p className="mt-2 text-xl font-black">{formatCurrency(payment.amount)}</p></Panel><Panel className="p-5"><p className="text-xs font-bold uppercase text-slate-400">Cổng thanh toán</p><p className="mt-2 font-black">{payment.provider}</p></Panel><Panel className="p-5"><p className="text-xs font-bold uppercase text-slate-400">Ngày tạo</p><p className="mt-2 font-bold">{formatBackendDateTime(payment.createdAt)}</p></Panel></div><Panel className="p-6"><dl className="grid gap-5 md:grid-cols-2"><div><dt className="text-xs font-bold uppercase text-slate-400">Order ID</dt><dd className="mt-2"><Link className="font-bold text-indigo-600" to={`/admin/orders/${payment.orderId}`}>#{payment.orderId}</Link></dd></div><div><dt className="text-xs font-bold uppercase text-slate-400">Transaction No</dt><dd className="mt-2 font-mono text-sm font-bold text-slate-800">{payment.transactionNo || "—"}</dd></div></dl>{payment.status !== "PENDING" && <p className="mt-6 rounded-xl bg-slate-50 p-3 text-xs font-semibold text-slate-600">Backend chỉ thực sự cập nhật payment khi trạng thái hiện tại là PENDING.</p>}</Panel></>;
}
