# Chọn profile mặc định là 'dev' nếu không cấu hình gì thêm
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Cấu hình chung cho JPA
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type.json_format_mapper=jackson

# 🌐 Đọc thông tin kết nối DB từ biến môi trường (Dùng chung cho cả dev và prod)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/aura_tech
spring.datasource.username=${DB_USERNAME:akira}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# KHÔNG ĐỂ MẶC ĐỊNH (FALLBACK) CHO CÁC CHUỖI MẬT TRÊN PROD
app.jwt.secret=${JWT_SECRET}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}