# Cho phép Hibernate tự cập nhật cấu trúc bảng dưới máy local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Bật tính năng tự động chạy dữ liệu mẫu từ file data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:data.sql