# TUYỆT ĐỐI KHÔNG TỰ SỬA BẢNG - CHỈ VALIDATE CẤU TRÚC
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# TUYỆT ĐỐI TẮT TÍNH NĂNG CHẠY FILE DATA.SQL
spring.sql.init.mode=never

app.auth.cookie.secure=${AUTH_COOKIE_SECURE:true}
